### ISSUE TITLE
Function `input` without arguments generates an error 

### ISSUE THREAD

**Issue by esyepesv** [kentdlee/JCoCo#1]
Using the virtual machine available [here](https://kentdlee.github.io/JCoCoPages/_build/html/_downloads/jcoco.zip), I am getting a "An Uncaught Exeption Ocuured" with the following program: 
````python
import disassembler
import sys

def main():
  print("enter a string: ")
  n = input()
  print(n)
if len(sys.argv) == 1:
    main()
else:
    disassembler.disassemble(main)
````

CC'ing @asr

**Comment by kentdlee** [comment]
While the disassembler can disassemble any Python program, the bytecode interpreter is not designed as a full replacement of Python. The error message is exactly as it should be. The input function in the bytecode interpreter expects 1 argument, a string (which is the prompt). So you have to get rid of your print and put the "enter a string: " as an argument to input. That will fix your problem. The bytecode interpreter threw the exception on the line that called the input function which is exactly as it should have. There was one space missing in the error message between got and 0. I fixed that.

**Comment by asr** [comment]
Thank you for the explanation and for fixing the typo. Please also fix the typo in the version available in [The JCoCo Virtual Machine](https://kentdlee.github.io/JCoCoPages/_build/html/index.html) page.
